use std::fs;
use std::path::Path;

fn main() {
    // Generate the HTML file with inlined CSS and JS for Tauri
    generate_frontend_html();

    // Copy PDF.js vendor files to frontend
    copy_vendor_files();

    tauri_build::build()
}

/// Generate index.html with inlined CSS and JS from markdown_preview_core sources.
///
/// The JS is split into:
/// - core.js: Shared UI functionality (TOC, themes, fuzzy finder, etc.)
/// - pdf-viewer.js: PDF.js based PDF viewer
/// - dictionary.js, ask-ai.js, settings-dialog.js, path-input.js: Feature modules
/// - tauri-app.js: Tauri-specific IPC and initialization
fn generate_frontend_html() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_path = Path::new(&manifest_dir).parent().unwrap();

    // Source files from crates/markdown_preview_core/js
    let js_dir = base_path.join("crates/markdown_preview_core/js");
    let html_template =
        fs::read_to_string(js_dir.join("index.html")).expect("Failed to read index.html template");

    // Load CSS files
    let styles_css =
        fs::read_to_string(js_dir.join("styles.css")).expect("Failed to read styles.css");
    let fuzzy_finder_css = fs::read_to_string(js_dir.join("fuzzy-finder.css"))
        .expect("Failed to read fuzzy-finder.css");
    let pdf_viewer_css =
        fs::read_to_string(js_dir.join("pdf-viewer.css")).expect("Failed to read pdf-viewer.css");
    let presentation_css = fs::read_to_string(js_dir.join("presentation.css"))
        .expect("Failed to read presentation.css");
    let diff_css = fs::read_to_string(js_dir.join("diff.css")).expect("Failed to read diff.css");
    let terminal_css =
        fs::read_to_string(js_dir.join("terminal.css")).expect("Failed to read terminal.css");
    let dictionary_css =
        fs::read_to_string(js_dir.join("dictionary.css")).expect("Failed to read dictionary.css");
    let ask_ai_css =
        fs::read_to_string(js_dir.join("ask-ai.css")).expect("Failed to read ask-ai.css");
    let themes_css =
        fs::read_to_string(js_dir.join("themes.css")).expect("Failed to read themes.css");

    // Load modular JS files
    let core_js = fs::read_to_string(js_dir.join("core.js")).expect("Failed to read core.js");
    let tooltips_js =
        fs::read_to_string(js_dir.join("tooltips.js")).expect("Failed to read tooltips.js");
    let search_js = fs::read_to_string(js_dir.join("search.js")).expect("Failed to read search.js");
    let diff_js = fs::read_to_string(js_dir.join("diff.js")).expect("Failed to read diff.js");
    let pdf_viewer_js = js_dir.join("pdf-viewer.js");
    let pdf_viewer_js = if pdf_viewer_js.exists() {
        fs::read_to_string(&pdf_viewer_js).expect("Failed to read pdf-viewer.js")
    } else {
        String::new()
    };
    let terminal_js = js_dir.join("terminal.js");
    let terminal_js = if terminal_js.exists() {
        fs::read_to_string(&terminal_js).expect("Failed to read terminal.js")
    } else {
        String::new()
    };
    let dictionary_js =
        fs::read_to_string(js_dir.join("dictionary.js")).expect("Failed to read dictionary.js");
    let ask_ai_js = fs::read_to_string(js_dir.join("ask-ai.js")).expect("Failed to read ask-ai.js");
    let settings_dialog_js = fs::read_to_string(js_dir.join("settings-dialog.js"))
        .expect("Failed to read settings-dialog.js");
    let path_input_js =
        fs::read_to_string(js_dir.join("path-input.js")).expect("Failed to read path-input.js");
    let tauri_app_js =
        fs::read_to_string(js_dir.join("tauri-app.js")).expect("Failed to read tauri-app.js");

    // Combine JS: core infrastructure first, then feature modules, then tauri-app (which has DOMContentLoaded)
    let combined_js = format!(
        "{core_js}\n\n{tooltips_js}\n\n{search_js}\n\n{diff_js}\n\n{pdf_viewer_js}\n\n{terminal_js}\n\n\
         {dictionary_js}\n\n{ask_ai_js}\n\n{settings_dialog_js}\n\n{path_input_js}\n\n\
         {tauri_app_js}"
    );

    // Combine CSS: base styles, then feature styles, then themes
    let combined_css = format!(
        "{styles_css}\n\n\
         {fuzzy_finder_css}\n\n{pdf_viewer_css}\n\n{presentation_css}\n\n\
         {diff_css}\n\n{terminal_css}\n\n{dictionary_css}\n\n{ask_ai_css}\n\n\
         {themes_css}"
    );

    // Replace placeholders
    let mut html = html_template;
    html = html.replace("/*__STYLES_CSS__*/", &combined_css);
    html = html.replace("/*__THEMES_CSS__*/", ""); // themes now included in combined_css
    html = html.replace("/*__APP_JS__*/", &combined_js);

    // Add auto-generated warning comment at the top
    let auto_gen_comment = r#"<!--
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY                                 │
    │                                                                             │
    │  This file is generated by build.rs from source files in:                   │
    │    crates/markdown_preview_core/js/                                          │
    │                                                                             │
    │  To make changes, edit the source files:                                    │
    │    - index.html           (HTML template)                                    │
    │    - styles.css           (base styles)                                      │
    │    - fuzzy-finder.css     (fuzzy finder styles)                              │
    │    - pdf-viewer.css       (PDF viewer styles)                                │
    │    - presentation.css     (presentation mode styles)                         │
    │    - diff.css             (diff overlay styles)                              │
    │    - terminal.css         (terminal panel styles)                            │
    │    - dictionary.css       (dictionary tool styles)                           │
    │    - ask-ai.css           (ask AI tool styles)                               │
    │    - themes.css           (theme styles)                                     │
    │    - core.js              (core UI functionality)                             │
    │    - tooltips.js          (tooltip system)                                   │
    │    - search.js            (fuzzy finder)                                     │
    │    - diff.js              (diff overlay)                                     │
    │    - pdf-viewer.js        (PDF viewer)                                       │
    │    - terminal.js          (terminal panel)                                   │
    │    - dictionary.js        (dictionary tool)                                  │
    │    - ask-ai.js            (ask AI tool)                                      │
    │    - settings-dialog.js   (settings dialog)                                  │
    │    - path-input.js        (path input / command palette)                     │
    │    - tauri-app.js         (Tauri-specific code)                              │
    │                                                                             │
    │  Then rebuild with: cargo build                                             │
    └─────────────────────────────────────────────────────────────────────────────┘
-->
"#;
    html = format!("{auto_gen_comment}{html}");

    // Create frontend directory for Tauri
    let frontend_dir = Path::new(&manifest_dir).join("frontend");
    fs::create_dir_all(&frontend_dir).expect("Failed to create frontend directory");

    // Write the generated HTML
    let output_path = frontend_dir.join("index.html");
    fs::write(&output_path, html).expect("Failed to write generated index.html");

    // Tell Cargo to rerun if source files change
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/index.html");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/styles.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/fuzzy-finder.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/pdf-viewer.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/presentation.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/diff.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/terminal.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/dictionary.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/ask-ai.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/themes.css");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/core.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/tooltips.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/search.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/diff.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/pdf-viewer.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/terminal.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/dictionary.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/ask-ai.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/settings-dialog.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/path-input.js");
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/tauri-app.js");
}

/// Copy PDF.js vendor files to frontend/vendor directory.
fn copy_vendor_files() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_path = Path::new(&manifest_dir).parent().unwrap();

    let source_vendor = base_path.join("crates/markdown_preview_core/js/vendor");
    let target_vendor = Path::new(&manifest_dir).join("frontend/vendor");

    // Create target vendor directory
    fs::create_dir_all(&target_vendor).expect("Failed to create frontend/vendor directory");

    // Copy main PDF.js files
    let files_to_copy = ["pdf.min.js", "pdf.worker.min.js"];
    for file in files_to_copy {
        let src = source_vendor.join(file);
        let dst = target_vendor.join(file);
        if src.exists() {
            fs::copy(&src, &dst).unwrap_or_else(|e| panic!("Failed to copy {file}: {e}"));
        }
    }

    // Copy cmaps directory
    let cmaps_src = source_vendor.join("cmaps");
    let cmaps_dst = target_vendor.join("cmaps");
    if cmaps_src.exists() {
        copy_dir_recursive(&cmaps_src, &cmaps_dst).expect("Failed to copy cmaps directory");
    }

    // Copy standard_fonts directory
    let fonts_src = source_vendor.join("standard_fonts");
    let fonts_dst = target_vendor.join("standard_fonts");
    if fonts_src.exists() {
        copy_dir_recursive(&fonts_src, &fonts_dst)
            .expect("Failed to copy standard_fonts directory");
    }

    // Rerun if vendor files change
    println!("cargo:rerun-if-changed=../crates/markdown_preview_core/js/vendor");
}

/// Recursively copy a directory and its contents.
fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;

    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }

    Ok(())
}
