[[language]]
name = "go"
filetype = ["go"]
root-markers = ["go.mod"]
language-servers = [ "gopls" ]

[[language]]
name = "rust"
filetype = ["rust"]
root-markers = ["Cargo.toml", "Cargo.lock"]
language-servers = [ "rust-analyzer" ]

[language-server]
gopls = { command = "gopls" }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
