[package]
name = "cli"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2021"
license = "MIT"
publish = false
homepage = "https://github.com/liuchengxu/vim-clap"
description = "CLI for vim-clap Rust backend"

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = ["derive"] }
futures = "0.3"
itertools = "0.10"
num_cpus = "1.13"
tokio = { version = "1.19", features = ["fs", "rt", "process", "macros", "rt-multi-thread", "sync", "time"] }
rayon = "1.5"
regex = "1"
serde_json = "1"
subprocess = { git = "https://github.com/hniksic/rust-subprocess" }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"

filter = { path = "../filter" }
icon = { path = "../icon" }
matcher = { path = "../matcher" }
maple_core = { path = "../maple_core" }
pattern = { path = "../pattern" }
printer = { path = "../printer" }
types = { path = "../types" }
utils = { path = "../utils" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
