[package]
name = "maple_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "parsing"] }
proc-macro2 = "1.0"
quote = "1.0"
deluxe = "0.5.0"
