use directories::{BaseDirs, ProjectDirs};
use once_cell::sync::Lazy;
use std::path::PathBuf;

/// Project directory for Vim Clap.
///
/// All the files generated by vim-clap are stored there.
pub static PROJECT_DIRS: Lazy<ProjectDirs> = Lazy::new(|| {
    ProjectDirs::from("org", "vim", "Vim Clap")
        .expect("Couldn't create project directory for vim-clap")
});

pub static BASE_DIRS: Lazy<BaseDirs> =
    Lazy::new(|| BaseDirs::new().expect("Failed to construct BaseDirs"));

pub fn clap_cache_dir() -> std::io::Result<PathBuf> {
    let cache_dir = PROJECT_DIRS.cache_dir();
    std::fs::create_dir_all(cache_dir)?;
    Ok(cache_dir.to_path_buf())
}
