[package]
name = "icon"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"
license = "MIT"
publish = false
homepage = "https://github.com/liuchengxu/vim-clap"
description = "Draw an icon according to the path name"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
