#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#  Whenever you change exactmatch_map.json or extension_map.json,
#  rerun this script to regenerate src/constants.rs:
#    ./update_constants.py
import json
import os

lines = [
    '// This file is generated by ../update_constants.py.',
    '// Do not edit thisfile manually.',
    '',
]
with open('extension_map.json', 'r') as f:
    disordered = json.load(f)
    sorted_dict = {k: disordered[k] for k in sorted(disordered)}

    keys = ','.join(map(lambda kv: '"%s"' % kv[0], sorted_dict.items()))
    vals = ','.join(map(lambda kv: '"%s"' % kv[1], sorted_dict.items()))
    lines.append('pub const EXTENSION: [&str; %d] = [%s];' %
                 (len(sorted_dict), keys))
    lines.append('pub const EXTENSION_ICON: [&str; %d] = [%s];' %
                 (len(sorted_dict), vals))

with open('exactmatch_map.json', 'r') as f:
    disordered = json.load(f)
    sorted_dict = {k: disordered[k] for k in sorted(disordered)}

    keys = ','.join(map(lambda kv: '"%s"' % kv[0], sorted_dict.items()))
    vals = ','.join(map(lambda kv: '"%s"' % kv[1], sorted_dict.items()))
    lines.append('pub const EXACTMATCH: [&str; %d] = [%s];' %
                 (len(sorted_dict), keys))
    lines.append('pub const EXACTMATCH_ICON: [&str; %d] = [%s];' %
                 (len(sorted_dict), vals))

with open('src/constants.rs', 'w') as f:
    f.write('\n'.join(lines))

os.system('rustfmt src/constants.rs')
