[package]
name = "utility"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2021"

[dependencies]
directories = "4.0"
memchr = "2.5"
simdutf8 = "0.1"

types = { path = "../types" }
