version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "rust:cargo"
    directory: "/pythonx/clap/fuzzymatch-rs"
    update_schedule: "weekly"
