use std::fs;
use std::path::Path;

fn main() {
    // Generate the HTML file with inlined CSS and JS for Tauri
    generate_frontend_html();

    // Copy PDF.js vendor files to frontend
    copy_vendor_files();

    tauri_build::build()
}

/// Generate index.html with inlined CSS and JS from maple_markdown sources.
///
/// The JS is split into:
/// - core.js: Shared UI functionality (TOC, themes, fuzzy finder, etc.)
/// - pdf-viewer.js: PDF.js based PDF viewer
/// - tauri-app.js: Tauri-specific IPC and initialization
fn generate_frontend_html() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_path = Path::new(&manifest_dir).parent().unwrap();

    // Source files from maple_markdown/js
    let js_dir = base_path.join("maple_markdown/js");
    let html_template =
        fs::read_to_string(js_dir.join("index.html")).expect("Failed to read index.html template");
    let styles_css =
        fs::read_to_string(js_dir.join("styles.css")).expect("Failed to read styles.css");
    let themes_css =
        fs::read_to_string(js_dir.join("themes.css")).expect("Failed to read themes.css");

    // Load modular JS files
    let core_js = fs::read_to_string(js_dir.join("core.js")).expect("Failed to read core.js");
    let pdf_viewer_js = js_dir.join("pdf-viewer.js");
    let pdf_viewer_js = if pdf_viewer_js.exists() {
        fs::read_to_string(&pdf_viewer_js).expect("Failed to read pdf-viewer.js")
    } else {
        String::new()
    };
    let terminal_js = js_dir.join("terminal.js");
    let terminal_js = if terminal_js.exists() {
        fs::read_to_string(&terminal_js).expect("Failed to read terminal.js")
    } else {
        String::new()
    };
    let tauri_app_js =
        fs::read_to_string(js_dir.join("tauri-app.js")).expect("Failed to read tauri-app.js");

    // Combine core + pdf-viewer + terminal + tauri-app for standalone app
    let combined_js = format!("{core_js}\n\n{pdf_viewer_js}\n\n{terminal_js}\n\n{tauri_app_js}");

    // Replace placeholders
    let mut html = html_template;
    html = html.replace("/*__STYLES_CSS__*/", &styles_css);
    html = html.replace("/*__THEMES_CSS__*/", &themes_css);
    html = html.replace("/*__APP_JS__*/", &combined_js);

    // Add auto-generated warning comment at the top
    let auto_gen_comment = r#"<!--
    ┌─────────────────────────────────────────────────────────────────────────────┐
    │  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY                                 │
    │                                                                             │
    │  This file is generated by build.rs from source files in:                   │
    │    ../maple_markdown/js/                                                    │
    │                                                                             │
    │  To make changes, edit the source files:                                    │
    │    - maple_markdown/js/index.html    (HTML template)                        │
    │    - maple_markdown/js/styles.css    (base styles)                          │
    │    - maple_markdown/js/themes.css    (theme styles)                         │
    │    - maple_markdown/js/core.js       (core UI functionality)                │
    │    - maple_markdown/js/terminal.js   (terminal panel)                       │
    │    - maple_markdown/js/tauri-app.js  (Tauri-specific code)                  │
    │    - maple_markdown/js/pdf-viewer.js (PDF viewer)                           │
    │                                                                             │
    │  Then rebuild with: cargo build                                             │
    └─────────────────────────────────────────────────────────────────────────────┘
-->
"#;
    html = format!("{auto_gen_comment}{html}");

    // Create frontend directory for Tauri
    let frontend_dir = Path::new(&manifest_dir).join("frontend");
    fs::create_dir_all(&frontend_dir).expect("Failed to create frontend directory");

    // Write the generated HTML
    let output_path = frontend_dir.join("index.html");
    fs::write(&output_path, html).expect("Failed to write generated index.html");

    // Tell Cargo to rerun if source files change
    println!("cargo:rerun-if-changed=../maple_markdown/js/index.html");
    println!("cargo:rerun-if-changed=../maple_markdown/js/styles.css");
    println!("cargo:rerun-if-changed=../maple_markdown/js/themes.css");
    println!("cargo:rerun-if-changed=../maple_markdown/js/core.js");
    println!("cargo:rerun-if-changed=../maple_markdown/js/tauri-app.js");
    println!("cargo:rerun-if-changed=../maple_markdown/js/terminal.js");
    println!("cargo:rerun-if-changed=../maple_markdown/js/pdf-viewer.js");
}

/// Copy PDF.js vendor files to frontend/vendor directory.
fn copy_vendor_files() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_path = Path::new(&manifest_dir).parent().unwrap();

    let source_vendor = base_path.join("maple_markdown/js/vendor");
    let target_vendor = Path::new(&manifest_dir).join("frontend/vendor");

    // Create target vendor directory
    fs::create_dir_all(&target_vendor).expect("Failed to create frontend/vendor directory");

    // Copy main PDF.js files
    let files_to_copy = ["pdf.min.js", "pdf.worker.min.js"];
    for file in files_to_copy {
        let src = source_vendor.join(file);
        let dst = target_vendor.join(file);
        if src.exists() {
            fs::copy(&src, &dst).unwrap_or_else(|e| panic!("Failed to copy {file}: {e}"));
        }
    }

    // Copy cmaps directory
    let cmaps_src = source_vendor.join("cmaps");
    let cmaps_dst = target_vendor.join("cmaps");
    if cmaps_src.exists() {
        copy_dir_recursive(&cmaps_src, &cmaps_dst).expect("Failed to copy cmaps directory");
    }

    // Copy standard_fonts directory
    let fonts_src = source_vendor.join("standard_fonts");
    let fonts_dst = target_vendor.join("standard_fonts");
    if fonts_src.exists() {
        copy_dir_recursive(&fonts_src, &fonts_dst)
            .expect("Failed to copy standard_fonts directory");
    }

    // Rerun if vendor files change
    println!("cargo:rerun-if-changed=../maple_markdown/js/vendor");
}

/// Recursively copy a directory and its contents.
fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;

    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }

    Ok(())
}
