[package]
name = "clap-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "clap-gui"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
parking_lot = { workspace = true }
directories = { workspace = true }

# Workspace crates
clap_search = { workspace = true }

[build-dependencies]
tauri-build = { version = "2", features = [] }
