[package]
name = "extracted_fzy"
edition = "2018"
version = "0.1.0"
authors = ["ImmConCon <43708554+ImmemorConsultrixContrarie@users.noreply.github.com>"]
description = "OS independent fzy algorithm from \"rff\" crate."
license = "MIT"
publish = false

# [dependencies]
